/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Admin;

import UI.Lecturers.Lecturers_ChangePassword_Form;
import UI.Lecturers.Lecturers_Statistics_Form;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author trung
 */
public class Admin_Manage_Form extends javax.swing.JFrame {

    /**
     * Creates new form AdminManage_Form
     */
    public Admin_Manage_Form() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    public void setUsername(String Username) {
        lbl_CurrentUsername.setText(Username);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbl_CurrentUsername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_CurrentUsername1 = new javax.swing.JLabel();
        lbl_CurrentUsername2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu6.setText("jMenu6");

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setPreferredSize(new java.awt.Dimension(1300, 700));

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(1200, 700));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(1200, 700));
        jDesktopPane1.setName(""); // NOI18N

        lbl_CurrentUsername.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jDesktopPane1.add(lbl_CurrentUsername);
        lbl_CurrentUsername.setBounds(1010, 30, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Chào,");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(950, 40, 50, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/Desktop3.png"))); // NOI18N
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1310, 660);

        lbl_CurrentUsername1.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jDesktopPane1.add(lbl_CurrentUsername1);
        lbl_CurrentUsername1.setBounds(1010, 20, 120, 30);

        lbl_CurrentUsername2.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jDesktopPane1.add(lbl_CurrentUsername2);
        lbl_CurrentUsername2.setBounds(1010, 20, 120, 30);

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(453, 43));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/user1.png"))); // NOI18N
        jMenu1.setText("Tài khoản");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/switch.png"))); // NOI18N
        jMenuItem6.setText("Đổi mật khẩu");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/log-out.png"))); // NOI18N
        jMenuItem5.setText("Đăng xuất");
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/debt.png"))); // NOI18N
        jMenu2.setText("Quản lý giảng viên");
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/teamwork.png"))); // NOI18N
        jMenuItem7.setText("Quản lý giảng viên");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/pie-chart.png"))); // NOI18N
        jMenu5.setText("Thống kê");
        jMenu5.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/analytics.png"))); // NOI18N
        jMenuItem8.setText("Thống kê");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuBar1.add(jMenu5);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/question.png"))); // NOI18N
        jMenu8.setText("Trợ giúp");
        jMenu8.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N

        jMenuItem1.setText("Giới thiệu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem1);

        jMenuItem2.setText("Hỗ trợ");
        jMenu8.add(jMenuItem2);

        jMenuItem3.setText("Hướng dẫn sử dụng");
        jMenu8.add(jMenuItem3);

        jMenuBar1.add(jMenu8);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/logout1.png"))); // NOI18N
        jMenu7.setText("Thoát");
        jMenu7.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

        Admin_Manager_Lectures Manage_Lecturers = new Admin_Manager_Lectures();
        jDesktopPane1.add(Manage_Lecturers);

        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = Manage_Lecturers.getSize();
        Manage_Lecturers.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        Manage_Lecturers.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        int c = JOptionPane.showConfirmDialog(this, "Thoát chương trình", "Bạn có muốn"
                + " thoát?", JOptionPane.YES_NO_OPTION);
        if (c == 0) {
            this.dispose();
        }

    }//GEN-LAST:event_jMenu7MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String message = "Tên sản phẩm: Phần mền thi Exam\n"
                + "Phiên bản: FPL Exam v1.0.1\n"
                + "Liên hệ với chúng tôi: FPL@edu.com.vn\n"
                + "Hệ thống: Windows 10 version 1903 running on amd64; Cp1252; "
                + "en_US (nb)\n"
                + "Website: caodang.poly.edu.vn\n"
                + "Số điện thoại: +(84) 987568698";
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Admin_ChangePassword_Form changePass = new Admin_ChangePassword_Form(lbl_CurrentUsername.getText());

        jDesktopPane1.add(changePass);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = changePass.getSize();
        changePass.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);

        jDesktopPane1.setVisible(true);
        changePass.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Lecturers_Statistics_Form Report = new Lecturers_Statistics_Form();
        jDesktopPane1.add(Report);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = Report.getSize();
        Report.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        Report.setVisible(true);
        Report.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Manage_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Manage_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Manage_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Manage_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Manage_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lbl_CurrentUsername;
    private javax.swing.JLabel lbl_CurrentUsername1;
    private javax.swing.JLabel lbl_CurrentUsername2;
    // End of variables declaration//GEN-END:variables
}
