/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Lecturers;

import DAO.ConnectDB;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author trung
 */
public class Lecturers_ChangePassword_Form extends javax.swing.JInternalFrame {

    /**
     * Creates new form Lecturers_ChangePassword_Form
     */
    String IDLecturers;

    public Lecturers_ChangePassword_Form(String IDLecturersGet) {
        initComponents();
        this.IDLecturers = IDLecturersGet;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_RePassNew = new javax.swing.JTextField();
        txt_PassNew = new javax.swing.JTextField();
        Btn_ChangePass = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 102));
        setClosable(true);
        setForeground(new java.awt.Color(255, 204, 102));
        setTitle("Đổi mật khẩu");

        jLabel1.setText("Mật khẩu mới:");

        jLabel3.setText("Nhập lại mật khẩu mới:");

        Btn_ChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/update.png"))); // NOI18N
        Btn_ChangePass.setText("Cập nhật");
        Btn_ChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ChangePassActionPerformed(evt);
            }
        });

        btn_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/logout.png"))); // NOI18N
        btn_Exit.setText("Thoát");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/reminder.png"))); // NOI18N

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Hãy nhớ mật khẩu mới!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_PassNew, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_RePassNew, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addComponent(Btn_ChangePass)
                .addGap(78, 78, 78)
                .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_PassNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_RePassNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_ChangePass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        int c = JOptionPane.showConfirmDialog(this, "Thoát?", "Bạn có muốn thoát?", JOptionPane.YES_NO_OPTION);
        if (c == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void Btn_ChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ChangePassActionPerformed

        if (txt_PassNew.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Không bỏ trống mật khẩu mới");
            return;
        }
        if (txt_RePassNew.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Không bỏ trống nhập lại mật khẩu mới");
            return;
        }
        if (!txt_PassNew.getText().equals(txt_RePassNew.getText())) {
            JOptionPane.showMessageDialog(this, "Mật khẩu phải giống nhau!");
            return;
        }

        String sql = "update Taikhoan set Matkhau = ? where Tentaikhoan = ?";
        ConnectDB connect = new ConnectDB();
        try {
            PreparedStatement prepe = connect.dungStament(sql);
            prepe.setString(1, txt_RePassNew.getText());
            prepe.setString(2, IDLecturers);
            prepe.executeUpdate();
            JOptionPane.showMessageDialog(this, "Cập nhật thàng công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi đổi mật khẩu: " + e);
        }


    }//GEN-LAST:event_Btn_ChangePassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_ChangePass;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_PassNew;
    private javax.swing.JTextField txt_RePassNew;
    // End of variables declaration//GEN-END:variables
}
