/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Lecturers;

import UI.Login_Form;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author trung
 */
public class Lecturers_Manage_Main_Form extends javax.swing.JFrame {

    public Lecturers_Manage_Main_Form() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);

    }

    public void setThongTinLecture(String magiangvien, String tenGiangVien) {
        lbl_nameLecture.setText(tenGiangVien);
        lbl_IDlecture.setText(magiangvien);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator5 = new javax.swing.JSeparator();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbl_nameLecture = new javax.swing.JLabel();
        lbl_IDlecture = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 600));
        setPreferredSize(new java.awt.Dimension(1341, 771));

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(1341, 671));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(1341, 671));
        jDesktopPane1.setRequestFocusEnabled(false);

        lbl_nameLecture.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jDesktopPane1.add(lbl_nameLecture);
        lbl_nameLecture.setBounds(1100, 20, 220, 30);

        lbl_IDlecture.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jDesktopPane1.add(lbl_IDlecture);
        lbl_IDlecture.setBounds(1100, 60, 220, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Mã giảng viên");
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(960, 60, 130, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Giảng viên:");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(960, 20, 130, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/background_Main.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1351, 681));
        jLabel1.setMinimumSize(new java.awt.Dimension(1351, 681));
        jLabel1.setPreferredSize(new java.awt.Dimension(1351, 681));
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(0, -10, 1350, 690);

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setForeground(new java.awt.Color(219, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jMenuBar1.setMaximumSize(new java.awt.Dimension(1350, 2));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(322, 33));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/user1.png"))); // NOI18N
        jMenu1.setText("Tài khoản");
        jMenu1.setFocusable(false);
        jMenu1.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/log-out.png"))); // NOI18N
        jMenuItem1.setText("Đăng xuất");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/management.png"))); // NOI18N
        jMenu2.setText("Quản lý");
        jMenu2.setFocusable(false);
        jMenu2.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/classroom.png"))); // NOI18N
        jMenuItem3.setText("Quản lý sinh viên");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);
        jMenu2.add(jSeparator3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/book.png"))); // NOI18N
        jMenuItem4.setText("Quản lý môn");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);
        jMenu2.add(jSeparator4);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/boss.png"))); // NOI18N
        jMenuItem9.setText("Quản lý lớp");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);
        jMenu2.add(jSeparator6);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/helpppp.png"))); // NOI18N
        jMenuItem6.setText("Quản lý câu hỏi");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/exam.png"))); // NOI18N
        jMenu6.setText("Kì thi");
        jMenu6.setFocusable(false);
        jMenu6.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/checklist.png"))); // NOI18N
        jMenuItem10.setText("Tạo kì thi");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem10);

        jMenuBar1.add(jMenu6);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/analytics.png"))); // NOI18N
        jMenu3.setText("Thống kê");
        jMenu3.setFocusable(false);
        jMenu3.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/pie-charttt.png"))); // NOI18N
        jMenuItem7.setText("Thống kê kết quả");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);
        jMenu3.add(jSeparator1);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/share.png"))); // NOI18N
        jMenuItem8.setText("Xuất thống kê");
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/information.png"))); // NOI18N
        jMenu4.setText("Hỗ trợ");
        jMenu4.setFocusable(false);
        jMenu4.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_Icon/exittt.png"))); // NOI18N
        jMenu5.setText("Thoát");
        jMenu5.setFocusable(false);
        jMenu5.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        this.dispose();
        Login_Form lg = new Login_Form();
        lg.show();

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Lecturers_Student_Manage_Form Student_Manage = new Lecturers_Student_Manage_Form();
        jDesktopPane1.add(Student_Manage);

        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = Student_Manage.getSize();
        Student_Manage.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);

        Student_Manage.setVisible(true);
        Student_Manage.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        Lecturers_Subject_Management_Form Manage_Subject = new Lecturers_Subject_Management_Form();
        jDesktopPane1.add(Manage_Subject);

        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = Manage_Subject.getSize();
        Manage_Subject.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);

        Manage_Subject.setVisible(true);
        Manage_Subject.show();


    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        Lecturers_Class_Management_Form Manage_Class = new Lecturers_Class_Management_Form();
        jDesktopPane1.add(Manage_Class);

        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = Manage_Class.getSize();
        Manage_Class.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);

        Manage_Class.setVisible(true);
        Manage_Class.show();


    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Lecturers_Question_Manage_Form ManageForm_subject = new Lecturers_Question_Manage_Form();
        jDesktopPane1.add(ManageForm_subject);

        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = ManageForm_subject.getSize();
        ManageForm_subject.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);

        ManageForm_subject.setVisible(true);
        ManageForm_subject.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        Lecturers_Create_Exam_Form Create_Exam = new Lecturers_Create_Exam_Form(lbl_IDlecture.getText());
        jDesktopPane1.add(Create_Exam);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension jInternalFrameSize = Create_Exam.getSize();
        Create_Exam.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);

        Create_Exam.setVisible(true);
        Create_Exam.show();

    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        int c = JOptionPane.showConfirmDialog(this, "Thoát chương trình", "Bạn có muốn thoát?", JOptionPane.YES_NO_OPTION);
        if (c == 0) {
            this.dispose();
        }

    }//GEN-LAST:event_jMenu5MouseClicked

    /**
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lecturers_Manage_Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lecturers_Manage_Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lecturers_Manage_Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lecturers_Manage_Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lecturers_Manage_Main_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JLabel lbl_IDlecture;
    private javax.swing.JLabel lbl_nameLecture;
    // End of variables declaration//GEN-END:variables
}
